Rails/HasAndBelongsToMany:
  Enabled: false

AllCops:
  NewCops: enable

require:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rails

Style/Documentation:
  Enabled: false

FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
