name: CICD

on:
  push:
    branches: [ main ]

jobs:
  test_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: cd booking_api && bundle install

      - name: RSpec
        run: cd booking_api && bundle exec rspec

      - name: Rubocop
        run: cd booking_api && bundle exec rubocop app/models app/controllers spec/factories spec/models spec/requests

  deploy:
    needs: test_lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy in Amazon EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            export PATH="$HOME/.rbenv/bin:$PATH" &&
            eval "$(rbenv init -)" &&
            cd ouryokukou_booking &&
            cd booking_api &&
            rm -f Gemfile.lock &&
            git pull &&
            bundle config set --local without 'development test' &&
            bundle install &&
            sudo systemctl restart myapp && sudo systemctl restart myfront
            '
