name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1

      - name: Install dependencies
        run: |
          cd booking_api
          bundle install

      - name: Run Tests
        run: |
          cd booking_api
          bundle exec rspec

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.HOSTNAME }}" > ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp -r ./booking_api ${USER_NAME}@${HOSTNAME}:~/ouryokukou_booking/
          ssh ${USER_NAME}@${HOSTNAME} <<EOF
            cd ~/ouryokukou_booking/booking_api
            bundle install
            bin/rails db:migrate RAILS_ENV=production
            sudo systemctl restart myapp
            sudo systemctl restart myfront
          EOF
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
